INSERT INTO USER ( ADDRESS, NAME, PASSWORD, PHONENUMBER, ROLE, USERNAME) VALUES ('local', 'admin', 'admin', '00000000', 'ADMIN', 'admin');
INSERT INTO USER ( ADDRESS, NAME, PASSWORD, PHONENUMBER, ROLE, USERNAME) VALUES ('local1', 'a', 'a', '00000001', 'PARTNER', 'a');
INSERT INTO USER ( ADDRESS, NAME, PASSWORD, PHONENUMBER, ROLE, USERNAME) VALUES ('local2', 'b', 'b', '00000002', 'WORKER', 'b');

INSERT INTO WORKSHEET ( PARTNER_ID, WORKER_ID) VALUES ('2', '3');

INSERT INTO RESERVATION ( CATEGORY, COMMENT, DATE, PARTNER_ID, WORKER_ID, WORKSHEET_ID) VALUES ('MOT', 'aaa', '2017-01-01', '2', '3', '1');

INSERT INTO PARTS ( NAME, PRICE) VALUES ('a', '100');

INSERT INTO PARTS_WORKSHEET( PARTS_ID, WORKSHEET_ID) VALUES ('1', '1');

UPDATE WORKSHEET SET RESERVATION_ID = 1